
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: databasesyncs.apps.quark.io
spec:
  group: apps.quark.io
  names:
    kind: DatabaseSyncs
    listKind: DatabaseSyncsList
    plural: databasesyncs
    singular: databasesync
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: The Schema for the ResourceSync API
          type: object
          properties:
            spec:
              description: DatabaseSyncSpec defines main field
              type: object
              properties:
                syncData:
                  type: string
                  enum:
                    - include-delete
                    - exclude-delete
                resourceType:
                  type: string
            status:
              description: Defines the observed state of ResourceSync
              type: object
              properties:
                state:
                  type: string
                  enum:
                    - Failed
                    - Processing
                    - Successful
                    - Created
